export default {
  title: '基础模板',
  type: 'template',
  key: 'base',
  photo: 'https://ks3-cn-beijing.ksyuncs.com/vform-static/form-samples/t1.png',
  uuId: 8,
  widgetList: [
    {
      title: '表单',
      type: 'form',
      key: 'form_0',
      noForm: true,
      children: [
        {
          title: '输入框',
          type: 'input',
          key: 'input_1',
          form: {
            _key: { label: '绑定key', type: 'input', value: 'name' },
            value: { label: '默认值', type: 'input', value: '' },
            label: { label: '标签文本', type: 'input', value: '姓名' },
            type: {
              label: '输入框类型',
              type: 'inputTypeSelect',
              value: 'text',
            },
            placeholder: {
              label: '占位内容',
              type: 'input',
              value: '请输入姓名',
            },
            clearable: { label: '可清空', type: 'switch', value: false },
            required: { label: '必填', type: 'switch', value: true },
            validate: { label: '校验规则', type: 'validateSelect', value: '' },
            maxlength: { label: '最大长度', type: 'input', value: '' },
            minlength: { label: '最小长度', type: 'input', value: '' },
            showWordLimit: {
              label: '显示字数限制',
              type: 'switch',
              value: false,
            },
          },
          component: 'element-plus-input',
          parent: 'form_0',
        },
        {
          title: '输入框',
          type: 'input',
          key: 'input_2',
          form: {
            _key: { label: '绑定key', type: 'input', value: 'age' },
            value: { label: '默认值', type: 'input', value: '' },
            label: { label: '标签文本', type: 'input', value: '年龄' },
            type: {
              label: '输入框类型',
              type: 'inputTypeSelect',
              value: 'password',
            },
            placeholder: {
              label: '占位内容',
              type: 'input',
              value: '请输入年龄',
            },
            clearable: { label: '可清空', type: 'switch', value: false },
            required: { label: '必填', type: 'switch', value: true },
            validate: { label: '校验规则', type: 'validateSelect', value: '' },
            maxlength: { label: '最大长度', type: 'input', value: '' },
            minlength: { label: '最小长度', type: 'input', value: '' },
            showWordLimit: {
              label: '显示字数限制',
              type: 'switch',
              value: false,
            },
          },
          component: 'element-plus-input',
          parent: 'form_0',
        },
        {
          title: '下拉框',
          type: 'select',
          key: 'select_5',
          component: 'element-plus-select',
          form: {
            _key: { label: '绑定key', type: 'input', value: 'job' },
            value: { label: '默认值', type: 'input', value: '' },
            label: { label: '标签文本', type: 'input', value: '职业' },
            options: {
              label: '选项配置',
              type: 'selectOptions',
              value: [
                { label: '医生', value: 1 },
                { label: '教师', value: 2 },
                { label: '公务员', value: 3 },
              ],
            },
            placeholder: {
              label: '占位内容',
              type: 'input',
              value: '请选择职业',
            },
            clearable: { label: '可清空', type: 'switch', value: false },
            required: { label: '必填', type: 'switch', value: false },
            multiple: { label: '多选', type: 'switch', value: false },
            filterable: { label: '可搜索', type: 'switch', value: false },
          },
          parent: 'form_0',
        },
      ],
      form: {
        '_key': { label: '数据对象', type: 'input', value: 'form_0' },
        'style.width': { label: '表单宽度', type: 'input', value: '' },
        'inline': { label: '行内模式', type: 'switch', value: false },
        'label-width': { label: '标签宽度', type: 'input', value: 'auto' },
        'label-position': {
          label: '标签位置',
          type: 'labelPosition',
          value: 'left',
        },
        'size': { label: '组件大小', type: 'formSize', value: 'default' },
      },
      component: 'element-plus-form',
    },
  ],
}
