export default {
  title: '来访表单',
  type: 'template',
  key: '1665722775859',
  photo: 'https://pic1.imgdb.cn/item/6349106216f2c2beb1b96ba0.jpg',
  uuId: 51,
  widgetList: [
    {
      title: '表单',
      type: 'form',
      key: 'form_0',
      noForm: true,
      children: [
        {
          title: '文字',
          type: 'text',
          key: 'text_9',
          component: 'element-plus-text',
          noForm: true,
          form: {
            content: { label: '内容', type: 'input', value: '来访登记' },
            size: {
              label: '字体大小',
              type: 'textSizeSelect',
              value: 'large',
            },
            block: { label: '块级', type: 'switch', value: true },
          },
          parent: 'form_0',
        },
        {
          title: '分割线',
          type: 'divider',
          key: 'divider_10',
          noForm: true,
          form: {
            content: { label: '分割线文案', type: 'input', value: '' },
          },
          component: 'element-plus-divider',
          parent: 'form_0',
        },
        {
          title: '网格',
          type: 'grid',
          key: 'grid_17',
          noForm: true,
          form: {
            gutter: { label: '栅格间隔', type: 'inputNumer', value: 0 },
          },
          children: [
            {
              title: 'col',
              type: 'col',
              key: 'col_18',
              noForm: true,
              form: {
                span: { label: '占位格数', type: 'inputNumer', value: 24 },
                offset: { label: '左侧间隔', type: 'inputNumer', value: 0 },
                push: { label: '向右移动', type: 'inputNumer', value: 0 },
                pull: { label: '向左移动', type: 'inputNumer', value: 0 },
              },
              children: [
                {
                  title: '输入框',
                  type: 'input',
                  key: 'input_1',
                  form: {
                    _key: { label: '绑定key', type: 'input', value: 'name' },
                    value: { label: '默认值', type: 'input', value: '' },
                    label: {
                      label: '标签文本',
                      type: 'input',
                      value: '姓名',
                    },
                    type: {
                      label: '输入框类型',
                      type: 'inputTypeSelect',
                      value: 'text',
                    },
                    placeholder: {
                      label: '占位内容',
                      type: 'input',
                      value: '请输入姓名',
                    },
                    clearable: {
                      label: '可清空',
                      type: 'switch',
                      value: false,
                    },
                    required: { label: '必填', type: 'switch', value: true },
                    validate: {
                      label: '校验规则',
                      type: 'validateSelect',
                      value: '',
                    },
                    maxlength: {
                      label: '最大长度',
                      type: 'input',
                      value: '',
                    },
                    minlength: {
                      label: '最小长度',
                      type: 'input',
                      value: '',
                    },
                    showWordLimit: {
                      label: '显示字数限制',
                      type: 'switch',
                      value: false,
                    },
                  },
                  component: 'element-plus-input',
                  parent: 'col_18',
                },
              ],
              component: 'element-plus-col',
              parent: 'grid_17',
            },
            {
              title: 'col',
              type: 'col',
              key: 'col_23',
              noForm: true,
              form: {
                span: { label: '占位格数', type: 'inputNumer', value: 12 },
                offset: { label: '左侧间隔', type: 'inputNumer', value: 0 },
                push: { label: '向右移动', type: 'inputNumer', value: 0 },
                pull: { label: '向左移动', type: 'inputNumer', value: 0 },
              },
              children: [
                {
                  title: '单选',
                  type: 'radio',
                  key: 'radio_8',
                  component: 'element-plus-radio',
                  form: {
                    _key: { label: '绑定key', type: 'input', value: 'sex' },
                    value: { label: '默认值', type: 'input', value: 1 },
                    label: {
                      label: '标签文本',
                      type: 'input',
                      value: '性别',
                    },
                    options: {
                      label: '选项配置',
                      type: 'listOptions',
                      value: {
                        男: 1,
                        女: 2,
                      },
                    },
                  },
                  parent: 'col_23',
                },
              ],
              component: 'element-plus-col',
              parent: 'grid_17',
            },
            {
              title: 'col',
              type: 'col',
              key: 'col_24',
              noForm: true,
              form: {
                span: { label: '占位格数', type: 'inputNumer', value: 12 },
                offset: { label: '左侧间隔', type: 'inputNumer', value: 0 },
                push: { label: '向右移动', type: 'inputNumer', value: 0 },
                pull: { label: '向左移动', type: 'inputNumer', value: 0 },
              },
              children: [
                {
                  title: '输入框',
                  type: 'input',
                  key: 'input_3',
                  form: {
                    _key: { label: '绑定key', type: 'input', value: 'age' },
                    value: { label: '默认值', type: 'input', value: '' },
                    label: {
                      label: '标签文本',
                      type: 'input',
                      value: '年龄',
                    },
                    type: {
                      label: '输入框类型',
                      type: 'inputTypeSelect',
                      value: 'number',
                    },
                    placeholder: {
                      label: '占位内容',
                      type: 'input',
                      value: '请输入年龄',
                    },
                    clearable: {
                      label: '可清空',
                      type: 'switch',
                      value: false,
                    },
                    required: { label: '必填', type: 'switch', value: true },
                    validate: {
                      label: '校验规则',
                      type: 'validateSelect',
                      value: '',
                    },
                    maxlength: {
                      label: '最大长度',
                      type: 'input',
                      value: '',
                    },
                    minlength: {
                      label: '最小长度',
                      type: 'input',
                      value: '',
                    },
                    showWordLimit: {
                      label: '显示字数限制',
                      type: 'switch',
                      value: false,
                    },
                  },
                  component: 'element-plus-input',
                  parent: 'col_24',
                },
              ],
              component: 'element-plus-col',
              parent: 'grid_17',
            },
            {
              title: 'col',
              type: 'col',
              key: 'col_26',
              noForm: true,
              form: {
                span: { label: '占位格数', type: 'inputNumer', value: 24 },
                offset: { label: '左侧间隔', type: 'inputNumer', value: 0 },
                push: { label: '向右移动', type: 'inputNumer', value: 0 },
                pull: { label: '向左移动', type: 'inputNumer', value: 0 },
              },
              children: [
                {
                  title: '输入框',
                  type: 'input',
                  key: 'input_4',
                  form: {
                    _key: { label: '绑定key', type: 'input', value: 'phone' },
                    value: { label: '默认值', type: 'input', value: '' },
                    label: {
                      label: '标签文本',
                      type: 'input',
                      value: '手机号',
                    },
                    type: {
                      label: '输入框类型',
                      type: 'inputTypeSelect',
                      value: 'number',
                    },
                    placeholder: {
                      label: '占位内容',
                      type: 'input',
                      value: '请输入手机号',
                    },
                    clearable: {
                      label: '可清空',
                      type: 'switch',
                      value: false,
                    },
                    required: { label: '必填', type: 'switch', value: true },
                    validate: {
                      label: '校验规则',
                      type: 'validateSelect',
                      value: {},
                    },
                    maxlength: {
                      label: '最大长度',
                      type: 'input',
                      value: '',
                    },
                    minlength: {
                      label: '最小长度',
                      type: 'input',
                      value: '',
                    },
                    showWordLimit: {
                      label: '显示字数限制',
                      type: 'switch',
                      value: false,
                    },
                  },
                  component: 'element-plus-input',
                  parent: 'col_26',
                },
              ],
              component: 'element-plus-col',
              parent: 'grid_17',
            },
            {
              title: 'col',
              type: 'col',
              key: 'col_25',
              noForm: true,
              form: {
                span: { label: '占位格数', type: 'inputNumer', value: 24 },
                offset: { label: '左侧间隔', type: 'inputNumer', value: 0 },
                push: { label: '向右移动', type: 'inputNumer', value: 0 },
                pull: { label: '向左移动', type: 'inputNumer', value: 0 },
              },
              children: [
                {
                  title: '输入框',
                  type: 'input',
                  key: 'input_5',
                  form: {
                    _key: {
                      label: '绑定key',
                      type: 'input',
                      value: 'address',
                    },
                    value: { label: '默认值', type: 'input', value: '' },
                    label: {
                      label: '标签文本',
                      type: 'input',
                      value: '家庭地址',
                    },
                    type: {
                      label: '输入框类型',
                      type: 'inputTypeSelect',
                      value: 'text',
                    },
                    placeholder: {
                      label: '占位内容',
                      type: 'input',
                      value: '请输入家庭地址',
                    },
                    clearable: {
                      label: '可清空',
                      type: 'switch',
                      value: true,
                    },
                    required: { label: '必填', type: 'switch', value: false },
                    validate: {
                      label: '校验规则',
                      type: 'validateSelect',
                      value: '',
                    },
                    maxlength: {
                      label: '最大长度',
                      type: 'input',
                      value: '',
                    },
                    minlength: {
                      label: '最小长度',
                      type: 'input',
                      value: '',
                    },
                    showWordLimit: {
                      label: '显示字数限制',
                      type: 'switch',
                      value: false,
                    },
                  },
                  component: 'element-plus-input',
                  parent: 'col_25',
                },
              ],
              component: 'element-plus-col',
              parent: 'grid_17',
            },
            {
              title: 'col',
              type: 'col',
              key: 'col_22',
              noForm: true,
              form: {
                span: { label: '占位格数', type: 'inputNumer', value: 12 },
                offset: { label: '左侧间隔', type: 'inputNumer', value: 0 },
                push: { label: '向右移动', type: 'inputNumer', value: 0 },
                pull: { label: '向左移动', type: 'inputNumer', value: 0 },
              },
              children: [
                {
                  title: '日期选择器',
                  type: 'date',
                  key: 'date_15',
                  component: 'element-plus-date',
                  form: {
                    _key: { label: '绑定key', type: 'input', value: 'date' },
                    value: { label: '默认值', type: 'input', value: '' },
                    label: {
                      label: '标签文本',
                      type: 'input',
                      value: '来访日期',
                    },
                    required: {
                      label: '必填',
                      type: 'switch',
                      value: false,
                    },
                    editable: {
                      label: '可输入',
                      type: 'switch',
                      value: true,
                    },
                    clearable: {
                      label: '可清空',
                      type: 'switch',
                      value: true,
                    },
                    type: {
                      label: '显示类型',
                      type: 'dateTypeSelect',
                      value: 'date',
                    },
                    placeholder: {
                      label: '占位内容',
                      type: 'input',
                      value: '请选择时间',
                    },
                    startPlaceholder: {
                      label: '开始占位内容',
                      type: 'input',
                      value: '开始时间',
                    },
                    endPlaceholder: {
                      label: '结束占位内容',
                      type: 'input',
                      value: '结束时间',
                    },
                    rangeSeparator: {
                      label: '范围分隔符',
                      type: 'input',
                      value: '-',
                    },
                    format: {
                      label: '显示格式',
                      type: 'input',
                      value: 'YYYY-MM-DD',
                    },
                    valueFormat: {
                      label: '输出格式',
                      type: 'input',
                      value: 'YYYY-MM-DD',
                    },
                  },
                  parent: 'col_22',
                },
              ],
              component: 'element-plus-col',
              parent: 'grid_17',
            },
            {
              title: 'col',
              type: 'col',
              key: 'col_19',
              noForm: true,
              form: {
                span: { label: '占位格数', type: 'inputNumer', value: 12 },
                offset: { label: '左侧间隔', type: 'inputNumer', value: 0 },
                push: { label: '向右移动', type: 'inputNumer', value: 0 },
                pull: { label: '向左移动', type: 'inputNumer', value: 0 },
              },
              children: [
                {
                  title: '时间选择器',
                  type: 'time',
                  key: 'time_20',
                  form: {
                    _key: { label: '绑定key', type: 'input', value: 'time' },
                    value: { label: '默认值', type: 'input', value: '' },
                    label: {
                      label: '标签文本',
                      type: 'input',
                      value: '来访时间',
                    },
                    required: {
                      label: '必填',
                      type: 'switch',
                      value: false,
                    },
                    editable: {
                      label: '可输入',
                      type: 'switch',
                      value: true,
                    },
                    clearable: {
                      label: '可清空',
                      type: 'switch',
                      value: true,
                    },
                    isRange: {
                      label: '是否范围选择',
                      type: 'switch',
                      value: false,
                    },
                    placeholder: {
                      label: '占位内容',
                      type: 'input',
                      value: '请选择时间',
                    },
                    startPlaceholder: {
                      label: '开始占位内容',
                      type: 'input',
                      value: '开始时间',
                    },
                    endPlaceholder: {
                      label: '结束占位内容',
                      type: 'input',
                      value: '结束时间',
                    },
                    rangeSeparator: {
                      label: '范围分隔符',
                      type: 'input',
                      value: '-',
                    },
                    format: {
                      label: '时间格式',
                      type: 'input',
                      value: 'HH:mm:ss',
                    },
                  },
                  component: 'element-plus-time',
                  parent: 'col_19',
                },
              ],
              component: 'element-plus-col',
              parent: 'grid_17',
            },
            {
              title: 'col',
              type: 'col',
              key: 'col_28',
              noForm: true,
              form: {
                span: { label: '占位格数', type: 'inputNumer', value: 24 },
                offset: { label: '左侧间隔', type: 'inputNumer', value: 0 },
                push: { label: '向右移动', type: 'inputNumer', value: 0 },
                pull: { label: '向左移动', type: 'inputNumer', value: 0 },
              },
              children: [
                {
                  title: '输入框',
                  type: 'input',
                  key: 'input_12',
                  form: {
                    _key: {
                      label: '绑定key',
                      type: 'input',
                      value: 'input_12',
                    },
                    value: { label: '默认值', type: 'input', value: '' },
                    label: {
                      label: '标签文本',
                      type: 'input',
                      value: '来访意向',
                    },
                    type: {
                      label: '输入框类型',
                      type: 'inputTypeSelect',
                      value: 'text',
                    },
                    placeholder: {
                      label: '占位内容',
                      type: 'input',
                      value: '请输入来访意向',
                    },
                    clearable: {
                      label: '可清空',
                      type: 'switch',
                      value: false,
                    },
                    required: { label: '必填', type: 'switch', value: false },
                    validate: {
                      label: '校验规则',
                      type: 'validateSelect',
                      value: '',
                    },
                    maxlength: {
                      label: '最大长度',
                      type: 'input',
                      value: '',
                    },
                    minlength: {
                      label: '最小长度',
                      type: 'input',
                      value: '',
                    },
                    showWordLimit: {
                      label: '显示字数限制',
                      type: 'switch',
                      value: false,
                    },
                  },
                  component: 'element-plus-input',
                  parent: 'col_28',
                },
              ],
              component: 'element-plus-col',
              parent: 'grid_17',
            },
            {
              title: 'col',
              type: 'col',
              key: 'col_27',
              noForm: true,
              form: {
                span: { label: '占位格数', type: 'inputNumer', value: 24 },
                offset: { label: '左侧间隔', type: 'inputNumer', value: 0 },
                push: { label: '向右移动', type: 'inputNumer', value: 0 },
                pull: { label: '向左移动', type: 'inputNumer', value: 0 },
              },
              children: [
                {
                  title: '多行文本',
                  type: 'textarea',
                  key: 'textarea_7',
                  form: {
                    _key: {
                      label: '绑定key',
                      type: 'input',
                      value: 'remake',
                    },
                    value: { label: '默认值', type: 'input', value: '' },
                    label: {
                      label: '标签文本',
                      type: 'input',
                      value: '备注',
                    },
                    placeholder: {
                      label: '占位内容',
                      type: 'input',
                      value: '请输入内容',
                    },
                    clearable: {
                      label: '可清空',
                      type: 'switch',
                      value: false,
                    },
                    required: { label: '必填', type: 'switch', value: false },
                    maxlength: {
                      label: '最大长度',
                      type: 'input',
                      value: '200',
                    },
                    minlength: {
                      label: '最小长度',
                      type: 'input',
                      value: '',
                    },
                    showWordLimit: {
                      label: '显示字数限制',
                      type: 'switch',
                      value: true,
                    },
                    rows: { label: '行数', type: 'input', value: '3' },
                    autosize: {
                      label: '自动调整大小',
                      type: 'switch',
                      value: true,
                    },
                    resize: {
                      label: '用户控制缩放',
                      type: 'resizeSelect',
                      value: 'both',
                    },
                  },
                  component: 'element-plus-textarea',
                  parent: 'col_27',
                },
              ],
              component: 'element-plus-col',
              parent: 'grid_17',
            },
          ],
          component: 'element-plus-grid',
          parent: 'form_0',
        },
      ],
      form: {
        '_key': { label: '数据对象', type: 'input', value: 'formData' },
        'style.width': { label: '表单宽度', type: 'input', value: '' },
        'inline': { label: '行内模式', type: 'switch', value: false },
        'label-width': { label: '标签宽度', type: 'input', value: 'auto' },
        'label-position': {
          label: '标签位置',
          type: 'labelPosition',
          value: 'right',
        },
        'size': { label: '组件大小', type: 'formSize', value: 'default' },
        'formType': {
          label: '表单类型',
          type: 'formTypeSelect',
          value: 'form',
        },
      },
      component: 'element-plus-form',
    },
  ],
}
