// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CgButton: typeof import('./src/components/form/CgButton.vue')['default']
    CgCard: typeof import('./src/components/form/CgCard.vue')['default']
    CgCheckbox: typeof import('./src/components/form/CgCheckbox.vue')['default']
    CgCode: typeof import('./src/components/form/CgCode.vue')['default']
    CgCol: typeof import('./src/components/form/CgCol.vue')['default']
    CgColor: typeof import('./src/components/form/CgColor.vue')['default']
    CgDate: typeof import('./src/components/form/CgDate.vue')['default']
    CgDivider: typeof import('./src/components/form/CgDivider.vue')['default']
    CgForm: typeof import('./src/components/form/CgForm.vue')['default']
    CgGrid: typeof import('./src/components/form/CgGrid.vue')['default']
    CgInput: typeof import('./src/components/form/CgInput.vue')['default']
    CgOptions: typeof import('./src/components/form/CgOptions.vue')['default']
    CgRadio: typeof import('./src/components/form/CgRadio.vue')['default']
    CgSelect: typeof import('./src/components/form/CgSelect.vue')['default']
    CgSwitch: typeof import('./src/components/form/CgSwitch.vue')['default']
    CgTable: typeof import('./src/components/form/CgTable.vue')['default']
    CgText: typeof import('./src/components/form/CgText.vue')['default']
    CgTextarea: typeof import('./src/components/form/CgTextarea.vue')['default']
    CgTime: typeof import('./src/components/form/CgTime.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    RenderComp: typeof import('./src/components/RenderComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
