// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CgCheckbox: typeof import('./src/components/form/CgCheckbox.vue')['default']
    CgCode: typeof import('./src/components/form/CgCode.vue')['default']
    CgColor: typeof import('./src/components/form/CgColor.vue')['default']
    CgInput: typeof import('./src/components/form/CgInput.vue')['default']
    CgOptions: typeof import('./src/components/form/CgOptions.vue')['default']
    CgSelect: typeof import('./src/components/form/CgSelect.vue')['default']
    CgSwitch: typeof import('./src/components/form/CgSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
